name: "Weather-Bot"
on:

  schedule:
    - cron: '0 14 * * *'

jobs:
  bot:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Install node'
        uses: actions/setup-node@v1
     
      - name: 'Install NPM dependemcies'
        run: npm install
      - name: "Run Code"
        run: node index.js
        env: 
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}
